# Generated by Django 2.0.1 on 2018-03-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='ERROR', max_length=10)),
                ('crn', models.IntegerField()),
                ('course_id', models.CharField(max_length=200)),
                ('course_attr', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('credit_hrs', models.CharField(max_length=200)),
                ('meet_time', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPN', 'OPEN'), ('CLSD', 'CLOSED')], default='OPEN', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_id', models.CharField(default='ERROR', max_length=10)),
                ('course_list', models.ManyToManyField(related_name='course_list', to='courses_database.Course')),
            ],
        ),
    ]
