# Generated by Django 2.0.1 on 2018-03-24 02:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('courses_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course_list',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
