# Generated by Django 2.0.1 on 2018-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_database', '0003_auto_20180324_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_number',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
