# Generated by Django 2.0.1 on 2018-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_database', '0004_auto_20180324_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.CharField(max_length=200),
        ),
    ]
