# Generated by Django 2.0.1 on 2018-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_database', '0005_auto_20180324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(max_length=200),
        ),
    ]
