# Generated by Django 2.0.1 on 2018-03-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_database', '0006_auto_20180324_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='ERROR', max_length=10)),
                ('course_id', models.CharField(default='ERROR', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='course_id',
            field=models.CharField(default='ERROR', max_length=10),
        ),
    ]
